# Generated by Django 3.1.2 on 2020-11-19 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to='news/%Y/%m/d%', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Subtitle')),
                ('full_info', models.TextField(verbose_name='Info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
    ]
