# Generated by Django 3.1.3 on 2020-12-14 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_type', models.CharField(choices=[('Top Advertisement', 'Top Advertisement'), ('Avarage Advertisement', 'Avarage Advertisement')], max_length=50, null=True, verbose_name='Type of advert')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('image', models.ImageField(null=True, upload_to='Advertisement/%Y/%m/%d/', verbose_name='Image')),
                ('slug', models.URLField(verbose_name='Link to Company website')),
                ('info', models.TextField(blank=True, verbose_name='Info')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_type', models.CharField(choices=[('Business News', 'Business News'), ('News', 'News')], max_length=50, null=True, verbose_name='Type of posts')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Subtitle')),
                ('full_info', models.TextField(verbose_name='Info')),
                ('image2', models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Next image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('popular', models.IntegerField(default=0, verbose_name='Views')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='news.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('text', models.TextField(max_length=300, verbose_name='Изох')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
