# Generated by Django 3.1.2 on 2020-11-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201119_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Next image'),
        ),
    ]
