# Generated by Django 3.1.2 on 2020-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Company name')),
                ('slug', models.SlugField(verbose_name='Link to Company website')),
                ('info', models.TextField(verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Advertising item',
                'verbose_name_plural': 'Advertising items',
            },
        ),
    ]
