# Generated by Django 3.1.2 on 2020-11-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='advertisement/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='ad',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Link to Company website'),
        ),
    ]
