# Generated by Django 3.1.2 on 2020-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201122_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='button',
            field=models.SlugField(blank=True, verbose_name='Link in button'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(verbose_name='Link to Company website'),
        ),
    ]
