# Generated by Django 3.1.3 on 2020-11-30 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201127_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('image', models.ImageField(null=True, upload_to='average_advertising/%Y/%m/%d/', verbose_name='Image')),
                ('slug', models.URLField(verbose_name='Link to Company website')),
                ('info', models.TextField(blank=True, verbose_name='Info')),
                ('button', models.URLField(blank=True, verbose_name='Link in button')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Avarage Advertisement',
                'verbose_name_plural': 'Avarage Advertisements',
            },
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Top Advertisement', 'verbose_name_plural': 'Top Advertisements'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='top_advertisement/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
