# Generated by Django 3.1.3 on 2020-12-02 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20201130_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Subtitle')),
                ('full_info', models.TextField(verbose_name='Info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Advert post',
                'verbose_name_plural': 'Advert posts',
            },
        ),
    ]
