# Generated by Django 3.1.3 on 2020-12-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20201203_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
