# Generated by Django 3.1.3 on 2020-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_news',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
