# Generated by Django 3.1.3 on 2020-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20201207_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type_post',
        ),
        migrations.AddField(
            model_name='news',
            name='choose_type',
            field=models.CharField(choices=[('Business News', 'Business'), ('News', 'News')], max_length=50, null=True, verbose_name='Type of posts'),
        ),
        migrations.DeleteModel(
            name='Type_news',
        ),
    ]
