# Generated by Django 3.1.3 on 2020-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20201207_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad_news',
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='ad',
            name='choose_type',
            field=models.CharField(choices=[('Top Advertisement', 'Top Advertisement'), ('Avarage Advertisement', 'Avarage Advertisement')], max_length=50, null=True, verbose_name='Type of advert'),
        ),
        migrations.AlterField(
            model_name='news',
            name='choose_type',
            field=models.CharField(choices=[('Business News', 'Business News'), ('News', 'News')], max_length=50, null=True, verbose_name='Type of posts'),
        ),
    ]
